version: '3.8'
services: 
  database:
    image: mongo
    restart: always 
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=my-username
      - MONGO_INITDB_ROOT_PASSWORD=my-root-password
    volumes: 
      - my_data:/data/db 
  node-web:
    build: 
      context: ./node-web
      dockerfile: Dockerfile
    depends_on: 
      - database
    volumes: 
      - /app/node_modules
      - ./node-web:/app 
    ports: 
      - "5000:5000"
  
volumes: 
  my_data: 